# Generated by Django 6.0.6 on 2026-07-12 20:16

import bboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[bboard.validators.validate_non_negative])),
                ('quantity', models.IntegerField(default=0, validators=[bboard.validators.validate_non_negative])),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[bboard.validators.validate_non_negative])),
            ],
        ),
    ]
