# Generated by Django 6.0.6 on 2026-07-12 20:32

import bboard.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название мороженого')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[bboard.validators.validate_non_negative], verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО родителя')),
            ],
        ),
        migrations.CreateModel(
            name='IceCreamKiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название киоска')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('ice_creams', models.ManyToManyField(blank=True, related_name='kiosks', to='bboard.icecream', verbose_name='Мороженое')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО ребёнка')),
                ('age', models.IntegerField(validators=[bboard.validators.validate_non_negative], verbose_name='Возраст')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bboard.parent', verbose_name='Родитель')),
            ],
        ),
    ]
