# Generated by Django 6.0.6 on 2026-07-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_icecream_parent_icecreamkiosk_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceCreamSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название набора')),
                ('flavors', models.JSONField(blank=True, default=list, verbose_name='Список мороженого')),
            ],
        ),
    ]
